### ISSUE TITLE
4swap 在【氢定投】上【优买计划】买入的四个LP token 在4swap中【我支持的流动池】-【历史记录】-三个净注入流动性显示为0，一个有显示的，不知道算不算BUG

### ISSUE THREAD

**Issue by LuoJun-Seven** [fox-one/4swap-reporter#2]
描述: 在【氢定投】上【优买计划】买入的四个LP token ：EOS-XIN（LP）、BTC-XIN（LP）、ETH-XIN（LP）、USDT-XIN（LP）
（1）能显示【净注入流动性】的EOS-XIN（LP）
EOS-XIN（LP）在4swap中【我的】
显示
我的占比
0.38335511 EOS
0.00735067 XIN
占总流动池比例
0.00%

EOS-XIN（LP）在4swap中【我支持的流动池】-【历史记录】-【净注入流动性】显示为
净注入流动性
0.00279914 EOS
0.00005432 XIN
净注入流动性 = 添加的沮动性总和 - 提取的流动性总和
添加的流动性总和
+0.00279914 EOS，+0.00005432 XIN
提取的注动性总和
0 EOS. 0 XIN
历史记录
添加流动性
3天前---------------------------$0.01
+0.00279914 EOS
+0.00005432 XIN

（2）显示【净注入流动性】为0的BTC-XIN（LP）
BTC-XIN（LP）在4swap中【我的】
显示
我的占比
0.00021994 BTC
0.02292319 XIN
占总流动池比例
0.00%

BTC-XIN（LP）在4swap中【我支持的流动池】-【历史记录】-【净注入流动性】显示为0
净注入流动性
0 BTC
0 XIN
净注入流动性 = 添加的沮动性总和 - 提取的流动性总和
添加的流动性总和
+0 BTC, +0 XIN
提取的流动性总和
0 BTC, 0 XIN

（3）显示【净注入流动性】为0的ETH-XIN（LP）
ETH-XIN（LP）在4swap中【我的】
显示
我的占比
0.00254987 ETH
0.00745291 XIN
占总流动池比例
0.00%

ETH-XIN（LP）在4swap中【我支持的流动池】-【历史记录】-【净注入流动性】显示为0
净注入流动性
0 ETH
0 XIN
净注入流动性 = 添加的流动性总和 - 提取的流动性总和
添加的流动性总和
+0 ETH, +0 XIN
提取的流动性总和
+0 ETH, +0 XIN
历史记录

（4）显示【净注入流动性】为0的USTD-XIN（LP）
USTD-XIN（LP）在4swap中【我的】
显示
我的占比
10.92729153 USDT
0.08173877 XIN
占总流动池比例
0.07%

USTD-XIN（LP）在4swap中【我支持的流动池】-【历史记录】-【净注入流动性】显示为0
净注入流动性
0 USDT
0 XIN
净注入流动性 = 添加的流动性总和 - 提取的流动性总和
添加的流动性总和
+0 USDT,+0 XIN
提取的流动性总和
0 USDT, 0 XIN
历史记录

（5）另外我直接在4swap注入的USDT-BOX流动性 有显示
USDT-BOX在4swap中【我的】
显示
我的占比
110.35416715 USDT
58.94193268 BOX
占总流动池比例
1.75%

USDT-BOX在4swap中【我支持的流动池】-【历史记录】-【净注入流动性】显示为
100 USDT
64.73544088 BOX
净注入流动性 = 添加的流动性总和 - 提取的流动性总和
添加的流动性总和
+100 USDT, +64.7354 BOX
提取的流动性总和
0 USDT, 0 BOX 
历史记录
添加流动性
1个月前
$200.83
+100 USDT@ERC20
+64.73544088 BOX
 
Mixin ID: 38846724 

影响: 受影响的用户触发 Bug 后，看到净注入流动性为0

客户端版本: XUEXI 1.4.4

客户端操作系统: Andriod 10

因为不知道怎么在gitUp上插入图片，所以把截图文字发上去了

补充：
补充（1）EOS-XIN（LP）在MIXIN钱包记录有【4SWAP】直接注入
后来在MIXIN钱包发现
EOS-XIN（LP）转账记录：
4swap LP Token EOS-XIN
0.05290185 sEOS-XIN
≈￥12.96
转出 丨 转入
转账记录
29/10/2020
【XUEXI ID:0 】转账    +0.05222639 sEOS-XIN （ 这笔应该是氢定投优买计划定投的 ）

28/10/2020
【4SWAP】 转账  +0.00038869 sEOS-XIN

26/10/2020
【4SWAP 中文社区】转账 +0.00009603 sEOS-XIN

23/10/2020
【4SWAP 中文社区】转账+0.00019074 sEOS-XIN

所以可能是sEOS-XIN 存在【4SWAP】直接注入，所以能显示净注入流动性。

补充（2）【4swap LP Token BTC-XIN】在MIXIN钱包记录没有【4SWAP】直接注入
【4swap LP Token BTC-XIN】在MIXIN钱包记录如下：
4swap LP Token BTC-XIN
0.00223907 sBTC-XIN
≈￥40.53
转出 丨 转入
转账记录
29/10/2020
【XUEXI ID:0 】+0.00149337.BTC-XIN
【XUEXI ID:0 】+0.0007457 .BTC-XIN （ 这2笔应该都是氢定投优买计划定投的 ）

补充（3）【4swap LP Token ETH-XIN】在MIXIN钱包记录没有【4SWAP】直接注入
【4swap LP Token ETH-XIN】在MIXIN钱包记录如下：
4swap LP Token ETH-XIN
0.00435096 sETH-XIN
≈￥13.19
转出 丨转入
转账记录
29/10/2020
【XUEXI ID:0 】转账+0.00435096 sETH-XIN（ 这笔应该也是氢定投优买计划定投的 ）

补充（4）【4swap LP Token USDT-XIN】在MIXIN钱包记录没有【4SWAP】直接注入
【4swap LP Token USDT-XIN】在MIXIN钱包记录如下：
4swap LP Token USDT-XIN
0.9334543 sUSDT-XIN
≈￥145.39
转出 丨转入
转账记录
31/10/2020
【XUEXI ID:0 】转账+0.17028085 sUSDT--XIN
【XUEXI ID:0 】转账+0.08527592 sUSDT-XIN
30/10/2020
【XUEXI ID:0 】转账+0.0851576 sUSDT-XIN
【XUEXI ID:0 】转账+0.08476772 SUSDT-XIN
【XUEXI ID:0 】转账+0.08464328 sUSDTXIN
【XUEXI ID:0 】转账+0.08464888 sUSDTXIN
29/10/2020
【XUEXI ID:0 】转账+0.0846689 sUSDTXIN
【XUEXI ID:0 】转账+0.1693378 sUSDTXIN
【XUEXI ID:0 】转账+0.08467335 sUSDTXIN
（ 这9笔应该也是氢定投优买计划定投的 ）

补充（5）【USDT-BOX】估计不是LP Token钱包没显示

总结：必须有【4SWAP】直接注入，就是有在【4SWAP】直接注入流动性的才显示【净注入流动性】不为0；
如果 只有在【氢定投优买计划】定投的，【净注入流动性】为0

**Comment by yiplee** [comment]
不是 bug，只有你在 4swap 注入流动性和提取流动性操作的记录才会显示在”历史记录“里面。

**Comment by cg-xuy** [comment]
不是 BUG， issue将会被关闭。
