### ISSUE TITLE
净流动性-折算 数据异常

### ISSUE THREAD

**Issue by Supertramp2020** [fox-one/4swap-reporter#3]
描述：
打开4swap~我的～btc-box~历史记录～净流动性加入-折合 显示9800多$，返回我的流动性只有5000多$

mixinID：38955266

影响：数据相差太大，看着挺爽，但不是真的价值那么多😄

重现方法：
打开4swap~我的～btc-box~历史记录～净流动性加入-折合 ，按市价计算，与我的流动性 界面的价值 相差太大

**Comment by yiplee** [comment]
这个已修复

**Comment by cg-xuy** [comment]
感谢提醒，奖励会在近期发放！希望继续支持！
